_wandb:
    value:
        cli_version: 0.25.1
        e:
            xfuqwkni36lf4b79yyuzv9zjxb8h8zl4:
                codePath: Untitled1.ipynb
                colab: https://colab.research.google.com/notebook#fileId=1TOuhP7dUXJtFgnRG_SV0_URlSOe7XeHZ
                cpu_count: 1
                cpu_count_logical: 2
                disk:
                    /:
                        total: "115658190848"
                        used: "23355846656"
                email: ali.adib@csic.es
                executable: /usr/bin/python3
                host: 365cc1d7c190
                memory:
                    total: "13605834752"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: Untitled1.ipynb
                python: CPython 3.12.13
                root: /content/drive/MyDrive/Proyecto_MLOps_ECG
                startedAt: "2026-04-22T13:43:33.689574Z"
                writerId: xfuqwkni36lf4b79yyuzv9zjxb8h8zl4
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 4
                - 5
                - 41
                - 49
                - 53
                - 63
                - 105
            "2":
                - 1
                - 4
                - 5
                - 41
                - 49
                - 53
                - 63
                - 105
            "3":
                - 2
                - 14
            "4": 3.12.13
            "5": 0.25.1
            "8":
                - 1
                - 12
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 5
lr:
    value: 0.001
nf:
    value: 64
target_samples:
    value: 20000
